Repository IgniteUI/grid-demos, pull requests merged in 2025-02, with the labels that each got.

#54 Fixed stretched dialog images
  projects/erp-hgrid/src/app/erp-hgrid-sample/erp-hgrid-sample.component.html
Labels: :white_check_mark: status: verified

#53 Refactor how themes are provided. Fix a bug with tab switching.
  package-lock.json
  package.json
  projects/erp-hgrid/package-lock.json
  projects/erp-hgrid/package.json
  projects/erp-hgrid/src/app/app.component.scss
  projects/erp-hgrid/src/app/app.component.ts
  projects/erp-hgrid/src/app/erp-hgrid-sample/erp-hgrid-sample.component.ts
  projects/erp-hgrid/src/index.html
  projects/erp-hgrid/src/styles.scss
  projects/finance-grid/package-lock.json
  projects/finance-grid/package.json
  projects/finance-grid/src/app/app.component.scss
  projects/finance-grid/src/app/app.component.ts
  projects/finance-grid/src/app/finance-grid/finance-grid.component.ts
  projects/finance-grid/src/index.html
  projects/finance-grid/src/styles.scss
  projects/fleet-management-grid/package-lock.json
  projects/fleet-management-grid/package.json
  projects/fleet-management-grid/src/app/app.component.scss
  projects/fleet-management-grid/src/app/app.component.ts
  projects/fleet-management-grid/src/app/fleet-management-grid/fleet-management-grid.component.ts
  projects/fleet-management-grid/src/index.html
  projects/fleet-management-grid/src/styles.scss
  projects/hr-portal/package-lock.json
  projects/hr-portal/package.json
  projects/hr-portal/src/app/app.component.scss
  projects/hr-portal/src/app/app.component.ts
  projects/hr-portal/src/app/hr-portal/hr-portal.component.scss
  projects/hr-portal/src/app/hr-portal/hr-portal.component.ts
  projects/hr-portal/src/index.html
  projects/hr-portal/src/styles.scss
  projects/sales-grid/package-lock.json
  projects/sales-grid/package.json
  projects/sales-grid/src/app/app.component.scss
  projects/sales-grid/src/app/app.component.ts
  projects/sales-grid/src/app/sales-grid/sales-grid.component.scss
  projects/sales-grid/src/app/sales-grid/sales-grid.component.ts
  projects/sales-grid/src/index.html
  projects/sales-grid/src/styles.scss
  src/app/app.component.scss
  src/app/views/erp-hgrid/erp-hgrid-view.component.html
  src/app/views/erp-hgrid/erp-hgrid-view.component.ts
  src/app/views/finance/finance-view.component.html
  src/app/views/finance/finance-view.component.scss
  src/app/views/finance/finance-view.component.ts
  src/app/views/fleet-management/fleet-management-view.component.html
  src/app/views/fleet-management/fleet-management-view.component.scss
  src/app/views/fleet-management/fleet-management-view.component.ts
  src/app/views/hr-portal/hr-portal-view.component.html
  src/app/views/hr-portal/hr-portal-view.component.scss
  src/app/views/hr-portal/hr-portal-view.component.ts
  src/app/views/sales/sales-view.component.html
  src/app/views/sales/sales-view.component.scss
  src/app/views/sales/sales-view.component.ts
  src/styles.scss
Labels: design: verified

#50 Fix fleet sample column width to remove scrollbar
  projects/fleet-management-grid/src/app/fleet-management-grid/fleet-management-grid.component.html
Labels: :x: status: awaiting-test

#56 Add home view and routing so grids can be open in standalone view without tabs.
  src/app/app.component.html
  src/app/app.component.scss
  src/app/app.component.ts
  src/app/app.routes.ts
  src/app/views/home/home.component.html
  src/app/views/home/home.component.scss
  src/app/views/home/home.component.ts
  src/server.ts
Labels: :white_check_mark: status: verified

#70 Fix horizontal flickering of samples
  src/app/views/erp-hgrid/erp-hgrid-view.component.scss
  src/app/views/finance/finance-view.component.scss
  src/app/views/fleet-management/fleet-management-view.component.scss
  src/app/views/home/home.component.scss
  src/app/views/hr-portal/hr-portal-view.component.scss
  src/app/views/sales/sales-view.component.scss
Labels: :white_check_mark: status: verified

#55 [Fleet Management] Add overlay close scroll strategy
  projects/fleet-management-grid/src/app/app.component.scss
  projects/fleet-management-grid/src/app/fleet-management-grid/fleet-management-grid.component.html
  projects/fleet-management-grid/src/app/fleet-management-grid/fleet-management-grid.component.scss
  projects/fleet-management-grid/src/app/fleet-management-grid/fleet-management-grid.component.ts
Labels: :white_check_mark: status: verified

#72 Fix area chart opacity
  projects/fleet-management-grid/src/app/fleet-management-grid/fleet-management-grid.component.html
Labels: :white_check_mark: status: verified, design: verified

#73 Improvements to the financial app
  projects/finance-grid/src/app/finance-grid/finance-grid.component.html
  projects/finance-grid/src/app/finance-grid/finance-grid.component.scss
  projects/finance-grid/src/app/finance-grid/finance-grid.component.ts
Labels: :white_check_mark: status: verified, design: verified

#64 Added new charts to ERP sample
  projects/erp-hgrid/src/app/data/dataModels.ts
  projects/erp-hgrid/src/app/data/erpData.ts
  projects/erp-hgrid/src/app/data/productOrdersTrendsData.ts
  projects/erp-hgrid/src/app/erp-hgrid-sample/erp-hgrid-sample.component.html
  projects/erp-hgrid/src/app/erp-hgrid-sample/erp-hgrid-sample.component.scss
  projects/erp-hgrid/src/app/erp-hgrid-sample/erp-hgrid-sample.component.ts
  projects/erp-hgrid/src/app/sales-trends-chart/sales-trends-chart.component.html
  projects/erp-hgrid/src/app/sales-trends-chart/sales-trends-chart.component.scss
  projects/erp-hgrid/src/app/sales-trends-chart/sales-trends-chart.component.ts
  projects/erp-hgrid/src/app/services/erp-data.service.ts
Labels: :white_check_mark: status: verified, design: verified

#77 Make disabled download button and link interactive.
  src/app/views/home/home.component.html
  src/app/views/home/home.component.scss
  src/app/views/home/home.component.ts
Labels: :white_check_mark: status: verified, design: verified

#80 fix(downloads): add download urls
  src/app/views/home/home.component.ts
Labels: :white_check_mark: status: verified

#85 Modify column widths so that asset column does not have huge whitespace
  projects/finance-grid/src/app/finance-grid/finance-grid.component.html
Labels: :white_check_mark: status: verified

#78 Update Sales Grid button design and add another view
  projects/fleet-management-grid/src/app/fleet-management-grid/fleet-management-grid.component.ts
  projects/sales-grid/src/app/sales-grid/sales-grid.component.html
  projects/sales-grid/src/app/sales-grid/sales-grid.component.ts
Labels: :white_check_mark: status: verified, design: verified
